### ISSUE TITLE
七牛云一键部署问题

### ISSUE THREAD

**Issue by lelehub** [httpsok/httpsok#11]
七牛云不支持一键部署，这个问题是因为平台没有开放接口是吗？
<img width="411" alt="image" src="https://github.com/httpsok/httpsok/assets/38939982/331664f5-4ab5-4481-b181-7dcb9e323a3a">

**Comment by tangweixin** [comment]
可以支持的，麻烦提供下对应的域名，我们确认下是什么问题。

**Comment by lelehub** [comment]
已经修复了哈，多谢。

**Comment by tangweixin** [comment]
哈哈，不客气的。
