### ISSUE TITLE
控制台如何删除已废弃的nginx

### ISSUE THREAD

**Issue by Emtier** [httpsok/httpsok#12]
如标题所示
目前控制台只能将自动部署禁用。没有删除设备的功能，现在控制台多个设备 有不用的测试设备需要删除

**Comment by tangweixin** [comment]
谢谢您的反馈：

后续版本我们会支持卸载后自动删除部署记录。

**Comment by tangweixin** [comment]
1.14.0 版本已经支持，卸载脚本后，自动删除控制台记录。

卸载命令： httpsok.sh -u
