### ISSUE TITLE
什么时候考虑增加百度智能云的cdn部署

### ISSUE THREAD

**Issue by muziqiu2** [httpsok/httpsok#14]
如题，作者开发的这个程序非常好，不过目前正在使用的百度智能云的cdn，官方也有相关的api文档，希望能够支持。

**Comment by tangweixin** [comment]
好的，谢谢您的反馈，我们尽快支持下。

**Comment by muziqiu2** [comment]
发现已经支持了，本问题结束，祝贵项目越来越好
