### ISSUE TITLE
希望能增加为全站加速DCDN 域名部署ssl证书

### ISSUE THREAD

**Issue by wabksw** [httpsok/httpsok#15]
### 现在dcdn生产使用场景也挺多的，建议也加上

**Comment by tangweixin** [comment]
您好，请问是哪个厂商的DCDN？

**Comment by wabksw** [comment]
阿里云的

**Comment by tangweixin** [comment]
好的，我们找时间对接下。

**Comment by tangweixin** [comment]
您好，阿里云的DCDN已经支持。

<img width="573" alt="image" src="https://github.com/user-attachments/assets/c07982e4-1291-4308-bc2c-281627bdb7d9">
