### ISSUE TITLE
自动续期的证书能否继续保持之前的品牌和加密方式

### ISSUE THREAD

**Issue by doahuw** [httpsok/httpsok#19]
申请的证书品牌原本是Let's Encrypt，加密方式是RSA。证书到期后自动申请的证书品牌变成Google，加密方式变成ECC了。在一些老服务器上访问使用google证书或使用ecc加密方式的网站会握手失败

**Comment by tangweixin** [comment]
谢谢您的反馈，这块我们优化一下。

**Comment by tangweixin** [comment]
这个已经优化好了。
