### ISSUE TITLE
能否支持私有化

### ISSUE THREAD

**Issue by eamd-wq** [httpsok/httpsok#2]
部分政企客户无法支持添加dns解析 目前续期用的1panel
作者这边能否有私有化版的推出 必打赏

**Comment by tangweixin** [comment]
政企具体是什么需求，方便详聊一下吗？

![image](https://github.com/httpsok/httpsok/assets/897400/a23b2899-adf5-4e02-9731-f0107e01d6b9)

**Comment by mouday** [comment]
如果是文件验证，可以试试：https://github.com/mouday/domain-admin
