### ISSUE TITLE
一些担忧和建议

### ISSUE THREAD

**Issue by Jack-Ywn** [httpsok/httpsok#21]
**1. Nginx Proxy Manager的证书导入的自动化支持**
我一直使用Nginx Proxy Manager、acme.sh等工具去颁发证书，此类工具要颁发谷歌的泛域名证书相对麻烦，而且有失败几率。
使用httpsok确实很方便快捷，我的web站点全部是通过Nginx Proxy Manager发布的，所以希望能支持对Nginx Proxy Manager自定义证书的到期更新。

**2. 提供免费版本的区别和选择指南**
希望作者能够详细说明免费版本与付费版本的区别，并给出选择指南。这将帮助潜在用户更好地理解每个版本的功能和限制，从而做出是否选择购买付费版本的决定。

**Comment by tangweixin** [comment]
谢谢您的反馈。

1. 我们是基于Linux系统的适配，所以理论上是支持Nginx Proxy Manager的，不太清楚您的具体诉求是什么。（如果是自签名证书，做自动更新意义不大）
2. 付费版本还在开发中，后续发布的话，又会有详细说明的。

**Comment by Jack-Ywn** [comment]
我通过httpsok颁发的泛域名证书，并且将证书导入到Nginx Proxy Manager中
![image](https://github.com/user-attachments/assets/d8f93f85-b440-4db3-956a-2d3c2816cb8e)
当httpsok颁发的泛域名证书到期的时候希望可以支持一键去更新Nginx Proxy Manager导入的证书文件（文件目录如下）
![image](https://github.com/user-attachments/assets/6d603620-b989-4f8b-b802-d3290ab459f8)

**Comment by tangweixin** [comment]
如果是nginx，直接运行控制台的 httpsok.sh 命令就可以。

您可以看一下这个快速开始： https://httpsok.com/doc/guide/quickstart.html
