### ISSUE TITLE
提建议如下

### ISSUE THREAD

**Issue by wang4386** [httpsok/httpsok#23]
1、增加对又拍云CDN/OSS支持
2、增加对多吉云CDN/OSS支持
3、支持1Panel面板容器化部署的OpenResty支持
4、邀请推荐可增添Nginx部署数量而不仅仅是通配符证书数量
5、免费版套餐建议增加nginx可部署数量
6、增加dnspod、腾讯云、阿里云、华为云、cloudflare等的自动化DNS设置

以上均个人见解，httpsock是个不错的证书管理工具，希望可以做到多平台覆盖

**Comment by tangweixin** [comment]
好的，非常感谢您的**反馈**。

我们会持续完善产品，希望能给大家提供简单、已用的产品。
