### ISSUE TITLE
云厂商的SecretID和SecretKey需要哪些权限

### ISSUE THREAD

**Issue by fulyaec** [httpsok/httpsok#24]
请问如果在阿里云上部署CDN证书的话，提供的SecretID和SecretKey需要哪些权限？

**Comment by tangweixin** [comment]
阿里云需要CDNFullAccess，还有云盾证书的权限。建议使用子账号，只开启最小权限。

**Comment by fulyaec** [comment]
> 阿里云需要CDNFullAccess，还有云盾证书的权限。建议使用子账号，只开启最小权限。

好的，谢谢！

**Comment by tangweixin** [comment]
不客气的。
