### ISSUE TITLE
可以支持群辉吗

### ISSUE THREAD

**Issue by lqbby** [httpsok/httpsok#28]

**Comment by tangweixin** [comment]
后期会考虑支持的。

**Comment by pisceakin** [comment]
+1 工具很好用，希望可以支持群晖的自动续签

**Comment by pisceakin** [comment]
> 后期会考虑支持的。

+1 工具很好用，希望可以支持群晖的自动续签

**Comment by tangweixin** [comment]
收到，我们安排开发下。 😄

**Comment by PAHTNOM233** [comment]
群晖+1，希望可以尽快开放出群晖的自动续签。

**Comment by tangweixin** [comment]
> 群晖+1，希望可以尽快开放出群晖的自动续签。

收到，我们尽快调高群晖版本优先级。

**Comment by tangweixin** [comment]
### 群晖已支持，开始进入内测阶段。

欢迎大家体验，有问题也可以随时和我们反馈。

<img width="718" alt="image" src="https://github.com/user-attachments/assets/b7487552-b644-491b-a109-4c673f24bcbb">

**Comment by tangweixin** [comment]
合并到一个工单：

https://github.com/httpsok/httpsok/issues/4
