### ISSUE TITLE
会支持到宝塔面板么

### ISSUE THREAD

**Issue by rrkai** [httpsok/httpsok#29]
跟宝塔面板对接上自动续签到证书就部署上去..因为有的网站会开腾讯云的cdn所以需要腾讯云那边的证书..每次只能去腾讯云续签后再手动部署更新到宝塔比较麻烦

**Comment by tangweixin** [comment]
支持宝塔面板的，可以参考下教程：https://httpsok.com/doc/reference/bt-install.html

CDN也是支持的，各大主流平台的CDN都支持

<img width="1237" alt="image" src="https://github.com/user-attachments/assets/3ff3c488-279c-4bb0-89fc-0ccfb4e963c0">

**Comment by rrkai** [comment]
> 支持宝塔面板的，可以参考下教程：https://httpsok.com/doc/reference/bt-install.html
> 
> CDN也是支持的，各大主流平台的CDN都支持
> 
> <img alt="image" width="1237" src="https://private-user-images.githubusercontent.com/897400/378076958-3ff3c488-279c-4bb0-89fc-0ccfb4e963c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDczMDcsIm5iZiI6MTcyOTQ0NzAwNywicGF0aCI6Ii84OTc0MDAvMzc4MDc2OTU4LTNmZjNjNDg4LTI3OWMtNGJiMC04OWZjLTBjY2ZiNGU5NjNjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMFQxNzU2NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDAyNWEzMTdkYTcxNjg0Zjc0ZGU5MmU1NWJjZGI2MzE3M2U3OGQxN2QwZGRjMjJjZTA5ZGI3ZGZlNWYxM2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Nzmvk3InKR-pSRpoWA5fnXTUUQsVB5Tzh7RJw2o_a1k">

如果是申请的泛域名证书呢...会自动把所有站点的证书更新么..例如*.11.cc证书..宝塔上面的网站有1.11.cc和2.11.cc站点..会一起更新么

**Comment by tangweixin** [comment]
是的，支持的。证书到期前15天就会自动更新
