### ISSUE TITLE
如何自动推送到阿里云的CDN？

### ISSUE THREAD

**Issue by luisxin** [httpsok/httpsok#3]
这两个地址好像都挂了
地址：https://auto-depoly.httpsok.com/

地址：https://ads.httpsok.com/

**Comment by tangweixin** [comment]
自动推送到阿里云的CDN，这个功能还在开发中。

谢谢您的关注。

**Comment by tangweixin** [comment]
您好，CDN和OSS自动部署都已经支持了。

谢谢您的反馈。

**Comment by tangweixin** [comment]
直接登陆控制台就可以看到了。
