### ISSUE TITLE
考虑一下，如何与群晖集成

### ISSUE THREAD

**Issue by mapleshadow** [httpsok/httpsok#4]
RT，目前可以手动解决，但还是太麻烦，考虑一下如何与群晖集成，这个市场很大

**Comment by tangweixin** [comment]
好的，谢谢您的反馈。 方便加微信具体聊一下吗？

**Comment by fusang1337** [comment]
请问有解决方案出来了么？

**Comment by tangweixin** [comment]
> 请问有解决方案出来了么？

这块具体的需求不太明确，方便的话，可以微信沟通下。 项目首页可以扫微信二维码。

**Comment by tangweixin** [comment]
### 群晖已上线

<img width="814" alt="image" src="https://github.com/user-attachments/assets/fb1ef3b8-f542-4d76-9afe-44e2869f038c">

**Comment by mban9584** [comment]
群晖NAS的OK了吗？？？？

**Comment by tangweixin** [comment]
**群晖已经支持了**

<img width="1208" alt="image" src="https://github.com/user-attachments/assets/259890d7-0218-49ff-8d6d-e3d43d40edde">

**Comment by tangweixin** [comment]
已支持
