### ISSUE TITLE
未来可以支持自定义证书存放路径证书名称和自定义应用重载命令吗？

### ISSUE THREAD

**Issue by xsllqs** [httpsok/httpsok#7]
未来可以支持自定义证书存放路径证书名称和自定义应用重载命令吗？

**Comment by tangweixin** [comment]
这是基于什么考虑呢，环境添加微信，一起探讨下。 微信二维码在项目的首页最下面

**Comment by zhumeishuai** [comment]
请问这个需求有考虑吗，比如用的容器，比如用的是其它程序向openresty这样
